import {
  Lot,
  StructureCost,
  Expense,
  InventoryItem,
  FeedConsumption,
  Weighing,
  Mortality,
  EggProduction,
  Incubation,
  Candling,
  EnergyMeasurement,
  Animal,
  Mating,
  Sale,
  Customer,
  Supplier,
  Asset,
  FarmAlert,
} from '@/types/farm'

export const initialLots: Lot[] = [
  {
    id: 'l-1',
    code: 'L-0001',
    name: 'Lote Poedeiras Isa Brown',
    type: 'Poedeiras',
    startDate: '2026-01-10',
    origin: 'Granja Matriz Sul',
    supplier: 'Avícola Santa Rita',
    breed: 'Isa Brown',
    initialQuantity: 120,
    currentQuantity: 116,
    initialAgeDays: 120,
    acquisitionCost: 3600,
    purpose: 'Produção de Ovos Comerciais',
    status: 'Ativo',
    notes: 'Início da fase de postura previsto para 140 dias.',
  },
  {
    id: 'l-2',
    code: 'L-0002',
    name: 'Lote Caipira Gigante 01',
    type: 'Frango caipira',
    startDate: '2026-02-01',
    origin: 'Incubação Própria',
    supplier: 'Sítio Sonho Roceiro',
    breed: 'Índio Gigante / Caipira',
    initialQuantity: 80,
    currentQuantity: 77,
    initialAgeDays: 1,
    acquisitionCost: 400,
    purpose: 'Engorda e Venda Vivos',
    status: 'Ativo',
    notes: 'Lote criado com ração inicial de alta proteína.',
  },
  {
    id: 'l-3',
    code: 'L-0003',
    name: 'Lote Corte Cobb 500',
    type: 'Frango de corte',
    startDate: '2026-01-20',
    origin: 'Incubatório Central',
    supplier: 'Aves do Vale',
    breed: 'Cobb 500',
    initialQuantity: 150,
    currentQuantity: 145,
    initialAgeDays: 1,
    acquisitionCost: 675,
    purpose: 'Abate e Venda por KG',
    status: 'Ativo',
    notes: 'Previsão de abate com 45 dias.',
  },
]

export const initialStructures: StructureCost[] = [
  {
    id: 'st-1',
    date: '2026-01-05',
    category: 'Madeira',
    description: 'Eucalipto tratado para estrutura do galinheiro',
    quantity: 40,
    unit: 'm',
    unitValue: 25,
    totalValue: 1000,
    supplier: 'Madeireira Serrana',
    paymentMethod: 'Pix',
    isPaid: true,
    center: 'Galinheiro Principal',
  },
  {
    id: 'st-2',
    date: '2026-01-08',
    category: 'Telhado',
    description: 'Telhas ecológicas 2.40x1.00m',
    quantity: 20,
    unit: 'unid',
    unitValue: 65,
    totalValue: 1300,
    supplier: 'Casa dos Materiais',
    paymentMethod: 'Cartão de Crédito',
    isPaid: true,
    center: 'Galinheiro Principal',
  },
  {
    id: 'st-3',
    date: '2026-01-12',
    category: 'Tela',
    description: 'Tela pinto hexagonal galinheiro 1.50m',
    quantity: 2,
    unit: 'rolo 50m',
    unitValue: 280,
    totalValue: 560,
    supplier: 'Agropecuária do Campo',
    paymentMethod: 'Pix',
    isPaid: true,
    center: 'Galinheiro Principal',
  },
]

export const initialExpenses: Expense[] = [
  {
    id: 'ex-1',
    date: '2026-02-02',
    category: 'Ração',
    description: 'Ração Inicial Postura 25kg',
    lotId: 'l-1',
    lotName: 'Lote Poedeiras Isa Brown',
    quantity: 4,
    unitValue: 85,
    totalValue: 340,
    supplier: 'Cooperativa Agrícola',
    paymentMethod: 'Pix',
    isPaid: true,
  },
  {
    id: 'ex-2',
    date: '2026-02-05',
    category: 'Medicamentos',
    description: 'Suplemento Vitamínico Aves 1L',
    lotId: 'l-2',
    lotName: 'Lote Caipira Gigante 01',
    quantity: 1,
    unitValue: 48,
    totalValue: 48,
    supplier: 'Veterinária Central',
    paymentMethod: 'Dinheiro',
    isPaid: true,
  },
]

export const initialInventory: InventoryItem[] = [
  {
    id: 'inv-1',
    name: 'Ração Postura 22% Proteína',
    category: 'Ração',
    unit: 'kg',
    currentStock: 150,
    minStock: 50,
    averageCost: 3.4,
    lastUpdated: '2026-02-08',
  },
  {
    id: 'inv-2',
    name: 'Milho Moído Fino',
    category: 'Milho',
    unit: 'kg',
    currentStock: 30,
    minStock: 100,
    averageCost: 1.8,
    lastUpdated: '2026-02-07',
  },
  {
    id: 'inv-3',
    name: 'Maravalha de Pinho (Cama)',
    category: 'Maravalha',
    unit: 'saco',
    currentStock: 12,
    minStock: 5,
    averageCost: 15.0,
    lastUpdated: '2026-02-01',
  },
]

export const initialFeed: FeedConsumption[] = [
  {
    id: 'fc-1',
    date: '2026-02-08',
    lotId: 'l-1',
    lotName: 'Lote Poedeiras Isa Brown',
    quantityKg: 14.5,
    inventoryItemId: 'inv-1',
    costPerKg: 3.4,
    totalCost: 49.3,
    notes: 'Alimentação matinal e vespertina',
  },
  {
    id: 'fc-2',
    date: '2026-02-08',
    lotId: 'l-2',
    lotName: 'Lote Caipira Gigante 01',
    quantityKg: 6.2,
    inventoryItemId: 'inv-2',
    costPerKg: 1.8,
    totalCost: 11.16,
    notes: 'Reforço de milho seco',
  },
]

export const initialWeighings: Weighing[] = [
  {
    id: 'w-1',
    date: '2026-02-01',
    lotId: 'l-3',
    lotName: 'Lote Corte Cobb 500',
    weighedCount: 15,
    totalWeightKg: 6.75,
    averageWeightKg: 0.45,
    ageDays: 12,
    dailyGainGrams: 32,
    notes: 'Aves apresentando bom ganho de carcaça',
  },
  {
    id: 'w-2',
    date: '2026-02-08',
    lotId: 'l-3',
    lotName: 'Lote Corte Cobb 500',
    weighedCount: 15,
    totalWeightKg: 14.1,
    averageWeightKg: 0.94,
    ageDays: 19,
    dailyGainGrams: 70,
    notes: 'Excelente uniformidade do lote',
  },
]

export const initialMortality: Mortality[] = [
  {
    id: 'm-1',
    date: '2026-01-15',
    lotId: 'l-1',
    lotName: 'Lote Poedeiras Isa Brown',
    quantity: 2,
    cause: 'Adaptação ao transporte',
    notes: 'Ocorrido no 5º dia pós chegada',
  },
  {
    id: 'm-2',
    date: '2026-02-03',
    lotId: 'l-2',
    lotName: 'Lote Caipira Gigante 01',
    quantity: 1,
    cause: 'Esmagamento acidental na fonte de calor',
    notes: 'Ajustada altura da campânula',
  },
]

export const initialEggs: EggProduction[] = [
  {
    id: 'egg-1',
    date: '2026-02-07',
    lotId: 'l-1',
    lotName: 'Lote Poedeiras Isa Brown',
    collected: 92,
    broken: 2,
    consumed: 4,
    sold: 60,
    incubated: 0,
    discarded: 1,
    notes: 'Taxa de postura em subida acelerada',
  },
  {
    id: 'egg-2',
    date: '2026-02-08',
    lotId: 'l-1',
    lotName: 'Lote Poedeiras Isa Brown',
    collected: 98,
    broken: 1,
    consumed: 3,
    sold: 72,
    incubated: 10,
    discarded: 0,
    notes: '10 ovos selecionados para a chocadeira',
  },
]

export const initialIncubations: Incubation[] = [
  {
    id: 'inc-1',
    code: 'I-0001',
    startDate: '2026-02-01',
    eggCount: 60,
    origin: 'Lote Caipira Selecionado',
    supplier: 'Produção Própria',
    breed: 'Caipira de Capoeira',
    eggCost: 90,
    incubatorName: 'Chocadeira Turbo 120 Ovos',
    targetTemp: 37.7,
    targetHumidity: 55,
    autoTurning: true,
    expectedHatchDate: '2026-02-22',
    status: 'Em andamento',
    energyCost: 28.5,
    notes: 'Primeiro ciclo de incubação do mês',
  },
]

export const initialCandlings: Candling[] = [
  {
    id: 'cand-1',
    incubationId: 'inc-1',
    date: '2026-02-07',
    day: 7,
    fertile: 52,
    infertile: 5,
    developing: 52,
    deadEmbryo: 1,
    discarded: 2,
    notes: 'Primeira ovoscopia realizada com lanterna LED',
  },
]

export const initialEnergy: EnergyMeasurement[] = [
  {
    id: 'eng-1',
    equipment: 'Chocadeira Turbo 120 Ovos',
    date: '2026-02-07',
    hours: 168,
    consumptionKwh: 28.5,
    ratePerKwh: 0.95,
    totalCost: 27.08,
    incubationId: 'inc-1',
  },
]

export const initialAnimals: Animal[] = [
  {
    id: 'an-1',
    code: 'GALO-01',
    sex: 'Macho',
    breed: 'Índio Gigante Pureza',
    lineage: 'Raça Pura Brasil',
    birthDate: '2025-05-10',
    origin: 'Criadouro Mogiana',
    weightKg: 4.8,
    status: 'Ativo',
    notes: 'Excelente envergadura de pernas e crista limpa',
  },
  {
    id: 'an-2',
    code: 'MATRIZ-05',
    sex: 'Fêmea',
    breed: 'Caipira Pesada',
    lineage: 'Linhagem Caipira',
    birthDate: '2025-06-01',
    origin: 'Produção Própria',
    weightKg: 3.2,
    status: 'Ativo',
    notes: 'Ótima taxa de postura de ovos bege escuro',
  },
]

export const initialMatings: Mating[] = [
  {
    id: 'mat-1',
    roosterCode: 'GALO-01',
    henCodes: ['MATRIZ-05', 'MATRIZ-06'],
    startDate: '2026-01-15',
    goal: 'Aumentar peso do peito e rusticidade',
    targetTrait: 'ganho de peso',
    status: 'Ativo',
  },
]

export const initialSales: Sale[] = [
  {
    id: 'sal-1',
    date: '2026-02-07',
    customerName: 'Dona Maria do Restaurante',
    product: 'Ovos',
    lotId: 'l-1',
    lotName: 'Lote Poedeiras Isa Brown',
    quantity: 60,
    unitPrice: 0.8,
    totalPrice: 48.0,
    paymentMethod: 'Pix',
    isPaid: true,
    notes: '2 dúzias de ovos caipiras vermelhos',
  },
  {
    id: 'sal-2',
    date: '2026-02-08',
    customerName: 'Seu João Açougue',
    product: 'Frangos vivos',
    lotId: 'l-2',
    lotName: 'Lote Caipira Gigante 01',
    quantity: 5,
    weightKg: 12.5,
    unitPrice: 18.0,
    totalPrice: 90.0,
    paymentMethod: 'Dinheiro',
    isPaid: true,
    notes: 'Frangos bem terminados',
  },
]

export const initialCustomers: Customer[] = [
  {
    id: 'c-1',
    name: 'Dona Maria do Restaurante',
    phone: '(35) 99876-1234',
    whatsapp: '5535998761234',
    city: 'Pouso Alegre - MG',
    notes: 'Compra ovos semanalmente toda sexta-feira',
  },
  {
    id: 'c-2',
    name: 'Seu João Açougue',
    phone: '(35) 98811-5544',
    whatsapp: '5535988115544',
    city: 'Pouso Alegre - MG',
    notes: 'Prefere frangos com mais de 2.2kg',
  },
]

export const initialSuppliers: Supplier[] = [
  {
    id: 'sup-1',
    name: 'Avícola Santa Rita',
    suppliedProduct: 'Pintainhas Poedeiras Isa Brown',
    phone: '(19) 3800-9900',
    city: 'Amparo - SP',
    notes: 'Fornecedor confiável com laudo sanitário',
  },
]

export const initialAssets: Asset[] = [
  {
    id: 'ast-1',
    name: 'Chocadeira Turbo 120 Ovos',
    category: 'Chocadeira',
    acquisitionDate: '2025-11-20',
    value: 1250,
    usefulLifeYears: 5,
    condition: 'Excelente',
    location: 'Sala de Incubação',
    notes: 'Controle digital de temperatura e umidade',
  },
  {
    id: 'ast-2',
    name: "Bomba d'água solar 1/2 CV",
    category: 'Bombas',
    acquisitionDate: '2025-12-10',
    value: 890,
    usefulLifeYears: 8,
    condition: 'Bom',
    location: 'Poço Caipira',
    notes: 'Alimenta bebedouros automáticos do galinheiro',
  },
]

export const initialAlerts: FarmAlert[] = [
  {
    id: 'alt-1',
    title: 'Milho Moído Fino com Estoque Baixo',
    description: 'Estoque atual (30kg) está abaixo do estoque mínimo (100kg).',
    type: 'estoque',
    date: '2026-02-08',
    isRead: false,
    modulePath: '/estoque',
  },
  {
    id: 'alt-2',
    title: 'Ovoscopia de 7 dias hoje!',
    description: 'A chocadeira "I-0001" requer ovoscopia hoje para descarte de ovos inférteis.',
    type: 'chocadeira',
    date: '2026-02-08',
    isRead: false,
    modulePath: '/chocadeira',
  },
]
